// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQEUSUyZTnquvzhg9xVFu5IjIG4Ly_bH0',
    appId: '1:958648486231:web:07b77611d591b79ddd1612',
    messagingSenderId: '958648486231',
    projectId: 'ghumnepal-9cec4',
    authDomain: 'ghumnepal-9cec4.firebaseapp.com',
    storageBucket: 'ghumnepal-9cec4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu0mc7LaMtDZ3QeZH3NBPQfwXRhE4MJzs',
    appId: '1:958648486231:android:c190a79fff93d7d9dd1612',
    messagingSenderId: '958648486231',
    projectId: 'ghumnepal-9cec4',
    storageBucket: 'ghumnepal-9cec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7GPEroeVgZdBnTUESua_9v4rtXZeX-tA',
    appId: '1:958648486231:ios:1390159e121434ecdd1612',
    messagingSenderId: '958648486231',
    projectId: 'ghumnepal-9cec4',
    storageBucket: 'ghumnepal-9cec4.firebasestorage.app',
    iosBundleId: 'com.example.ghumNepal',
  );
}
